// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0XeLjBVcykncvFLe_a_8wJFTxogK18gQ',
    appId: '1:336916956114:web:9e73f18cf7fc99575dfe0b',
    messagingSenderId: '336916956114',
    projectId: 'ecanteen-2101-firmanardiansyah',
    authDomain: 'ecanteen-2101-firmanardiansyah.firebaseapp.com',
    storageBucket: 'ecanteen-2101-firmanardiansyah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW56-HnkEwSf6SgylPTHBp7wVzJPx9nBM',
    appId: '1:336916956114:android:5ca11e3812d9fc925dfe0b',
    messagingSenderId: '336916956114',
    projectId: 'ecanteen-2101-firmanardiansyah',
    storageBucket: 'ecanteen-2101-firmanardiansyah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzVIUu5zg5MnyUcsAb_2u6wwM30ekD1g',
    appId: '1:336916956114:ios:f1d5521e1d8f34165dfe0b',
    messagingSenderId: '336916956114',
    projectId: 'ecanteen-2101-firmanardiansyah',
    storageBucket: 'ecanteen-2101-firmanardiansyah.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );
}
